# Generated by Django 2.1.7 on 2019-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190703_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='replace_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
