# Generated by Django 2.1.7 on 2019-07-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_document_time_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time_calc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
