# Generated by Django 2.1.7 on 2019-07-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_document_time_calc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='time',
            new_name='time_original',
        ),
    ]
