# Generated by Django 2.2.3 on 2019-07-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190720_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField(blank=True, null=True)),
                ('place_convert', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('name_convert', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
