# Generated by Django 2.2.3 on 2019-07-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_convertdocument'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConvertDocument',
            new_name='DocumentConvert',
        ),
    ]
