# Generated by Django 2.2.3 on 2019-07-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190724_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name_convert',
            field=models.TextField(blank=True, null=True),
        ),
    ]
