# Generated by Django 2.2.3 on 2019-07-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_document_name_convert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name_convert',
            new_name='name_origin',
        ),
    ]
