# Generated by Django 2.1.7 on 2019-08-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190725_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='region',
            field=models.TextField(default='1'),
        ),
    ]
